version: '3'

services:
    server:
        image: php:7.1-apache
        volumes:
          - ./www-server:/var/www/html

    client:
        image: php:7.1-apache
        volumes:
          - ./www-client:/var/www/html
        ports:
          - 666:80
        links:
          - server
