version: '3'

services:
    web:
        image: php:7.1-apache
        volumes:
          - ./www:/var/www/html
        environment:
          VIRTUAL_HOST: app2.localhost

networks:
  default:
    external:
      name: multiple-applications
